PSP Versuch 1 etwas weite ausgeführt
htwr-aachen/htwr-aachen.de pull request #49
Opened 2024-06-19 22:35 UTC by Zetabite

2024-06-20 14:03 UTC, NilEis requested changes
siehe kommentare

2024-06-20 17:00 UTC, Zetabite commented on summaries/deddebme/psp/ErsterVersuch.mdx
> +In der roten Box findet ihr zwei Kabel, Blau und Rot. Konvention in der Elektrotechnik ist: Rot ist Plus, Blau ist Minus. Zudem habt ihr noch ein drittes rotes Kabel das nicht wie die anderen beiden
Den gibts auch in blau an einigen plätzen

2024-06-20 17:00 UTC, Zetabite commented on summaries/deddebme/psp/ErsterVersuch.mdx
> +tags: [PSP, Versuch 1, ATmega 644, ADDA, DAW, DAC]
Jo

2024-06-20 17:00 UTC, Zetabite commented on summaries/deddebme/psp/ErsterVersuch.mdx
> +Bitte dreht den Spannungsregler (das ist dieser Linke Knauf an der Spannungsquelle) auf maximal 6 V (Volt). Mehr brauchen wir nicht. Den Rechten Regler müsst ihr so einstellen das wir ungefähr 200 mA
Ja, sollte man betonen

2024-06-21 22:39 UTC, jonsch318 approved these changes

2024-06-23 07:50 UTC, jonsch318 approved these changes

2024-06-24 17:00 UTC, NilEis approved these changes

2024-06-26 20:43 UTC, merged